# Generated by Django 5.2.17 on 2026-09-30 10:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_submission_teacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtractionRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('engine', models.CharField(max_length=100)),
                ('model_version', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('NEEDS_REVIEW', 'Needs review'), ('FAILED', 'Failed')], default='PENDING', max_length=30)),
                ('raw_text', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='extraction_runs', to='reviews.documentversion')),
            ],
        ),
        migrations.CreateModel(
            name='ExtractedField',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('field_key', models.CharField(max_length=100)),
                ('raw_value', models.TextField(blank=True)),
                ('normalized_value', models.TextField(blank=True)),
                ('confidence', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('page_number', models.PositiveIntegerField(blank=True, null=True)),
                ('evidence_text', models.TextField(blank=True)),
                ('bounding_box', models.JSONField(blank=True, null=True)),
                ('review_status', models.CharField(choices=[('AUTO_ACCEPTED', 'Auto accepted'), ('NEEDS_REVIEW', 'Needs review'), ('REJECTED', 'Rejected')], default='NEEDS_REVIEW', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fields', to='reviews.extractionrun')),
            ],
        ),
    ]
