# Generated by Django 5.2.17 on 2026-09-30 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_extractionrun_extractedfield'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendationrun',
            name='idempotency_key',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddConstraint(
            model_name='recommendationrun',
            constraint=models.UniqueConstraint(fields=('submission', 'idempotency_key'), name='uniq_submission_recommendation_key'),
        ),
    ]
