# Generated by Django 5.2.17 on 2026-09-30 11:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_notification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RuleMappingVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mapping_code', models.CharField(max_length=100)),
                ('version', models.PositiveIntegerField(default=1)),
                ('source_course', models.CharField(max_length=255)),
                ('target_course_code', models.CharField(max_length=100)),
                ('mapping_data', models.JSONField(default=dict)),
                ('source_reference', models.CharField(max_length=500)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('APPROVED', 'Approved'), ('RETIRED', 'Retired')], default='DRAFT', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_rule_mappings', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_rule_mappings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('mapping_code', '-version'),
                'constraints': [models.UniqueConstraint(fields=('mapping_code', 'version'), name='uniq_mapping_version')],
            },
        ),
    ]
