# Generated by Django 5.2.17 on 2026-09-30 11:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0006_rulemappingversion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('code', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='CurriculumVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version_label', models.CharField(max_length=255)),
                ('source_file', models.CharField(max_length=500)),
                ('source_sha256', models.CharField(max_length=64)),
                ('source_sheet', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('APPROVED', 'Approved'), ('RETIRED', 'Retired')], default='DRAFT', max_length=20)),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='curricula', to='reviews.program')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('raw_code', models.CharField(blank=True, max_length=100)),
                ('raw_name', models.CharField(max_length=500)),
                ('credits', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('course_type', models.CharField(blank=True, max_length=100)),
                ('assessment', models.CharField(blank=True, max_length=255)),
                ('source_row', models.PositiveIntegerField()),
                ('source_cells', models.JSONField(default=dict)),
                ('review_status', models.CharField(default='PENDING', max_length=20)),
                ('curriculum', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='courses', to='reviews.curriculumversion')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('curriculum', 'source_row'), name='uniq_curriculum_source_row')],
            },
        ),
        migrations.CreateModel(
            name='HistoricalDecision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_sha256', models.CharField(max_length=64)),
                ('source_file', models.CharField(max_length=500)),
                ('source_sheet', models.CharField(max_length=255)),
                ('source_row', models.PositiveIntegerField()),
                ('source_key_hash', models.CharField(blank=True, max_length=64)),
                ('program_code', models.CharField(blank=True, max_length=100)),
                ('course_code', models.CharField(blank=True, max_length=100)),
                ('course_name', models.CharField(blank=True, max_length=500)),
                ('decision_raw', models.CharField(blank=True, max_length=255)),
                ('decision', models.CharField(blank=True, max_length=30)),
                ('source_cells', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('PENDING', 'Pending review'), ('APPROVED', 'Approved precedent'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_note', models.TextField(blank=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('source_sha256', 'source_sheet', 'source_row'), name='uniq_historical_source_row')],
            },
        ),
        migrations.AddConstraint(
            model_name='curriculumversion',
            constraint=models.UniqueConstraint(fields=('source_sha256', 'source_sheet'), name='uniq_curriculum_source_sheet'),
        ),
    ]
