# Generated by Django 5.2.17 on 2026-09-30 13:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0009_extractedfield_human_accepted'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendationrun',
            name='curriculum_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='reviews.curriculumversion'),
        ),
        migrations.CreateModel(
            name='ExtractedCourseRow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('prior_credits', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='course_rows_as_credits', to='reviews.extractedfield')),
                ('prior_grade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='course_rows_as_grade', to='reviews.extractedfield')),
                ('source_course_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='course_rows_as_code', to='reviews.extractedfield')),
                ('source_course_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='course_rows_as_name', to='reviews.extractedfield')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='extracted_course_rows', to='reviews.submission')),
                ('target_course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evidence_rows', to='reviews.course')),
            ],
        ),
    ]
