# Generated by Django 5.2.17 on 2026-09-30 13:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0010_course_evidence_rows_and_curriculum_snapshot'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='extractedcourserow',
            constraint=models.UniqueConstraint(fields=('submission', 'source_course_name', 'prior_grade', 'prior_credits', 'target_course'), name='uniq_submission_course_evidence_row'),
        ),
    ]
