# Generated by Django 5.2.17 on 2026-09-30 13:48

from django.db import migrations, models


def mark_latest_run_current(apps, schema_editor):
    Run = apps.get_model("reviews", "RecommendationRun")
    submission_ids = list(Run.objects.values_list("submission_id", flat=True).distinct())
    for submission_id in submission_ids:
        run = Run.objects.filter(submission_id=submission_id).order_by("-created_at", "-pk").first()
        if run:
            Run.objects.filter(pk=run.pk).update(is_current=True)


def clear_current_runs(apps, schema_editor):
    apps.get_model("reviews", "RecommendationRun").objects.update(is_current=False)


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0011_unique_course_evidence_rows'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendationrun',
            name='is_current',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(mark_latest_run_current, clear_current_runs),
        migrations.AddConstraint(
            model_name='recommendationrun',
            constraint=models.UniqueConstraint(condition=models.Q(('is_current', True)), fields=('submission',), name='uniq_current_recommendation_run'),
        ),
    ]
