# Generated by Django 5.2.17 on 2026-09-30 16:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0012_current_recommendation_run'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(default='PENDING', max_length=20)),
                ('stage', models.CharField(default='QUEUED', max_length=30)),
                ('message', models.CharField(blank=True, max_length=1000)),
                ('worker_token', models.CharField(max_length=36)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('result', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='reviews.recommendationrun')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='analysis_jobs', to='reviews.submission')),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('status__in', ['PENDING', 'RUNNING'])), fields=('submission',), name='uniq_active_analysis_job')],
            },
        ),
    ]
